title: HGN Tax Prep
description: "Tax preparation, accounting, and business advisory services in Severance, Colorado. Right on the money."
url: "https://hansnelson31.github.io"
baseurl: "/taxprep-preview"

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - README.md
